version: "2.4"

volumes:
  kong_data: {}

networks:
  kong-net:
    driver: bridge
    ipam:
     config:
      - subnet: 192.168.45.0/28
        gateway: 192.168.45.1

services:
  kong-migrations:
    image: "kong:latest"
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
    networks:
      - kong-net
    restart: on-failure

  kong-migrations-up:
    image: "kong:latest"
    command: kong migrations up && kong migrations finish
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
    networks:
      - kong-net
    restart: on-failure

  #######################################
  # Kong: API management
  #######################################
  kong:
    image: "kong:latest"
    depends_on:
      - kong-migrations
    environment:
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
    networks:
      kong-net:
        ipv4_address: 192.168.45.10
    ports:
      - "8000:8000/tcp"
      - "8001/tcp"
      - "8443:8443/tcp"
      - "8444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure

  #######################################
  # Postgres: For Kong
  #######################################
  kong-database:
    image: postgres:9.5
    environment:
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_USER: kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
    networks:
      kong-net:
        ipv4_address: 192.168.45.12
    volumes:
      - kong_data:/var/lib/postgresql/data

  #######################################
  # Konga: Konga GUI
  #######################################
  konga:
    image: "pantsel/konga:latest"
    # Konga config
    restart: always
    networks:
      kong-net:
        ipv4_address: 192.168.45.11
    environment:
      TOKEN_SECRET: test-konga
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_PORT: 5432
      DB_DATABASE: kong
      DB_USER: kong
      DB_PASSWORD: kong
    depends_on:
      - kong-database
    ports:
      - "1337:1337/tcp"